### PR TITLE
Error handling

### LINKED ISSUE #232: OdraError
Errors are numbers.

Users should be able to define their own errors. Possible code:
```rust
pub enum Erc20Error {
    InsufficientBalance = 1,
    InsufficientAllowance = 2
}

impl From<Erc20Error> for OdraError {
    fn from(error: Erc20Error) -> Self {
        OdraError::user(error as u32)
    }
}
```

Users should be able to easily test errors.
```rust
assert_eq!(erc20.try_transfer(bob, 10.into()), Err(Erc20Error::InsufficientBalance));
```

Error code spaces similar to existing impl.

### PR DESCRIPTION
**Pull request by kpob**
Resolves #232

### CODE REVIEW

File: odra-core/src/host_env.rs [hunk 1]
```diff
@@ -18,6 +18,10 @@ impl HostEnv {
         HostEnv { backend }
     }
 
+    pub fn error(&self) -> Option<OdraError> {
```
Comment (kubaplas) [inline odra-core/src/host_env.rs]: Why do we need this function?

**Review by kubaplas — APPROVED** [review]

File: odra-core/src/host_env.rs (hunk 1 above)
Comment (kpob) [reply odra-core/src/host_env.rs]: It had already been there when I took it over. But having `try_*` functions and `env.last_call_result()` soon, I think we don't need it,
