### PR TITLE
Try to read user errors from the schema on livenet

### LINKED ISSUE #333: Handle deploy failure for `try_` methods.
From #258 
Don't panic when deploy fails when using try_ methods on livenet

### LINKED ISSUE #467: Errors mapping in HostEnv
At this moment if a contract fails, a user gets just the error number, eg
`🤦  ERROR : Deploy "f58fd84a62ca7ecab050299ab807475119be2b622c9d25de23f341bb6d4fdd3d" failed with error: "User error: 60001".` on livenet client.

Should be possible to take advantage of the schema file, find the error number, and print the error name.

If the error is an Odra internal error, also should be mapped to a human-readable form.

### PR DESCRIPTION
**Pull request by kpob**
## Summary by CodeRabbit

- **New Features**
  - Added error handling improvements for user and execution errors.
  - Introduced contract name registration functionality.

- **Bug Fixes**
  - Updated error code ranges to prevent conflicts.

- **Improvements**
  - Enhanced schema definitions with new error types and swapped field names for clarity.
  - Modified methods for better error handling and contract registration.

- **Refactor**
  - Replaced `Address::from_str` with `Address::new` for consistency.

- **Documentation**
  - Updated contract schema with new structs, errors, and entry points for improved clarity and functionality.

### CODE REVIEW

File: odra-casper/rpc-client/src/casper_client/error.rs [hunk 1]
```diff
@@ -0,0 +1,221 @@
+use anyhow::{anyhow, Result};
+use odra_core::{ExecutionError, OdraError};
+use serde_json::Value;
+use std::{fs, path::PathBuf};
+
+use crate::log;
+
+pub(crate) fn find(contract_name: &str, error_msg: &str) -> Result<(String, OdraError)> {
+    let schema_path = find_schema_file_path(contract_name)?;
+    let schema = fs::read_to_string(schema_path)?;
```
Comment (zie1ony) [inline odra-casper/rpc-client/src/casper_client/error.rs:13]: Why don't you parse it directly to `ContractSchema` from `odra-schema` crate?

File: odra-casper/rpc-client/src/casper_client/error.rs [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+    }
+}
+
+#[inline]
+fn is_internal_error(error_num: u16) -> bool {
+    error_num >= ExecutionError::UserErrorTooHigh.code()
+}
+
+fn get_internal_error_name(error_num: u16) -> (String, OdraError) {
+    match error_num {
```
Comment (zie1ony) [inline odra-casper/rpc-client/src/casper_client/error.rs]: Maybe some macro to simplify this?

File: odra-casper/rpc-client/src/casper_client/error.rs [hunk 3]
```diff
@@ -0,0 +1,221 @@
...
+        ),
+        x if x == ExecutionError::UserErrorTooHigh.code() => (
+            "ExecutionError::UserErrorTooHigh".to_string(),
+            ExecutionError::UserErrorTooHigh.into()
+        ),
+        _ => panic!("Unknown execution error code: {}", error_num)
+    }
+}
+
+fn find_schema_file_path(contract_name: &str) -> Result<PathBuf> {
```
Comment (zie1ony) [inline odra-casper/rpc-client/src/casper_client/error.rs]: I'd move it to `odra-schema` crate. It can be reused this way.

**Review by zie1ony — APPROVED** [review]
