### PR TITLE
Contracts related enhancements 

### LINKED ISSUE #522: OdraCLI: Create `resources` directory if it doesn't exist. Allow of spec resources dir via paramenter.
If `deploy` is called without `resources` dir it errors:
```
🤦  ERROR : Contract read error: Couldn't read file

Caused by:
    0: Couldn't read file
    1: No such file or directory (os error 2)
```

In addition if it is used by compiled binary it will be handy to specify resources directory for `deployed_contracts.toml`. `--resources` or `-r`

```
just cli -r resources/deployed_contracts_2.toml deploy
```

### LINKED ISSUE #556: OdraCLI: load or deploy helper method
Provide a method that checks `deployed-resources.toml` if the contract exists.

### PR DESCRIPTION
**Pull request by kpob**
Add load or deploy capability - #556 
Setting custom path to a toml file storing deployed contracts - #522

## Summary by CodeRabbit

- **New Features**
  - Added support for specifying a custom path to the deployed contracts file via a new CLI argument.
  - Improved contract registration by loading contracts from the specified path at runtime.
  - Introduced a deployment helper that can load or deploy contracts as needed.

- **Enhancements**
  - Streamlined contract management and registration within the CLI.
  - Improved handling of contract updates and file paths for deployed contracts.

### CODE REVIEW

File: odra-cli/src/args.rs [hunk 1]
```diff
@@ -10,6 +10,7 @@ use crate::{types, CustomTypeSet};
 
 pub const ARG_ATTACHED_VALUE: &str = "attached_value";
 pub const ARG_GAS: &str = "gas";
+pub const ARG_CONTRACTS: &str = "contracts";
```
Comment (zie1ony) [inline odra-cli/src/args.rs]: Maybe we name it `contracts-toml`? and then file with contract would be `contracts.toml` instead of `deployed_contracts.toml`?

File: odra-cli/src/lib.rs [hunk 2]
```diff
@@ -193,12 +225,24 @@ impl OdraCli {
...
     }
 
     /// Runs the CLI and parses the input.
     pub fn run(self) {
         let matches = self.main_cmd.get_matches();
+        // Check if the user provided a custom contracts path.
+        let path = args::read(&matches, ARG_CONTRACTS, PathBuf::from_str).ok();
+        // Init contracts container with the provided path or default to the resources directory.
+        let container = DeployedContractsContainer::new(path.clone())
+            .expect("Failed to create or load the deployed contracts container");
```
Comment (zie1ony) [inline odra-cli/src/lib.rs]: Use `prettycli::error`

**Review by zie1ony — APPROVED** [review]
